["FLASH:BroadcastJoin:Internal"]
error = '''
Broadcast Join internal error.
'''

["FLASH:BroadcastJoin:TooManyColumns"]
error = '''
Number of columns to read exceeds limit.
'''

["FLASH:Coprocessor:BadRequest"]
error = '''
Bad TiDB coprocessor request.
'''

["FLASH:Coprocessor:Internal"]
error = '''
TiFlash Coprocessor internal error.
'''

["FLASH:Coprocessor:MemoryLimitExceeded"]
error = '''
TiFlash memory limit exceeded.
'''

["FLASH:Coprocessor:Unimplemented"]
error = '''
Some features are unimplemented.
'''

["FLASH:DDL:ExchangePartitionError"]
error = '''
EXCHANGE PARTITION error.
'''

["FLASH:DDL:Internal"]
error = '''
TiFlash DDL internal error.
'''

["FLASH:DDL:MissingTable"]
error = '''
Table information is missing in TiFlash or TiKV.
'''

["FLASH:DDL:TableTypeNotMatch"]
error = '''
Table type in TiFlash is different from that in TiKV.
'''

["FLASH:Decimal:Overflow"]
error = '''
Decimal value overflow.
'''

["FLASH:DeltaTree:Internal"]
error = '''
DeltaTree internal error.
'''

["FLASH:Encryption:Internal"]
error = '''
Encryption internal error.
'''

["FLASH:Expression:DivisionByZero"]
error = '''
Division by 0.
'''

["FLASH:MPP:Internal"]
error = '''
MPP internal error.
'''

["FLASH:PageStorage:FileSizeNotMatch"]
error = '''
Some files' size don't match their metadata.
'''

["FLASH:Table:NotExists"]
error = '''
Table does not exist.
'''

["FLASH:Table:SchemaVersionError"]
error = '''
Schema version of target table in TiFlash is different from that in query.
'''

["FLASH:Table:SyncError"]
error = '''
Schema synchronize error.
'''

["FLASH:Types:Truncated"]
error = '''
Data is truncated during conversion.
'''

["FLASH:Types:WrongValue"]
error = '''
Input value is in wrong format
'''

