# Copyright 2023 PingCAP, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

["FLASH:BroadcastJoin:Internal"]
error = '''
Broadcast Join internal error.
'''

["FLASH:BroadcastJoin:TooManyColumns"]
error = '''
Number of columns to read exceeds limit.
'''

["FLASH:Checksum:DataCorruption"]
error = '''
Checksum hash mismatch was detected.
'''

["FLASH:Checksum:IOFailure"]
error = '''
There are failed IO operations during checksum loading or writing.
'''

["FLASH:Checksum:Internal"]
error = '''
Checksum internal error.
'''

["FLASH:Checksum:Missing"]
error = '''
Checksum info for disk I/O checksum was expected but not found.
'''

["FLASH:Coprocessor:BadRequest"]
error = '''
Bad TiDB coprocessor request.
'''

["FLASH:Coprocessor:Internal"]
error = '''
TiFlash Coprocessor internal error.
'''

["FLASH:Coprocessor:MemoryLimitExceeded"]
error = '''
TiFlash memory limit exceeded.
'''

["FLASH:Coprocessor:RegionError"]
error = '''
Region is unavailable.
'''

["FLASH:Coprocessor:Unimplemented"]
error = '''
Some features are unimplemented.
'''

["FLASH:DDL:ExchangePartitionError"]
error = '''
EXCHANGE PARTITION error.
'''

["FLASH:DDL:Internal"]
error = '''
TiFlash DDL internal error.
'''

["FLASH:DDL:MissingTable"]
error = '''
Table information is missing in TiFlash or TiKV.
'''

["FLASH:DDL:StaleSchema"]
error = '''
Schema is stale and need to reload all schema.
'''

["FLASH:DDL:TableTypeNotMatch"]
error = '''
Table type in TiFlash is different from that in TiKV.
'''

["FLASH:Decimal:Overflow"]
error = '''
Decimal value overflow.
'''

["FLASH:DeltaTree:Internal"]
error = '''
DeltaTree internal error.
'''

["FLASH:Encryption:Internal"]
error = '''
Encryption internal error.
'''

["FLASH:Expression:DivisionByZero"]
error = '''
Division by 0.
'''

["FLASH:MPP:Internal"]
error = '''
MPP internal error.
'''

["FLASH:PageStorage:FileSizeNotMatch"]
error = '''
Some files' size don't match their metadata.
'''

["FLASH:Table:NotExists"]
error = '''
Table does not exist.
'''

["FLASH:Table:SchemaVersionError"]
error = '''
Schema version of target table in TiFlash is different from that in query.
'''

["FLASH:Table:SyncError"]
error = '''
Schema synchronize error.
'''

["FLASH:Types:Truncated"]
error = '''
Data is truncated during conversion.
'''

["FLASH:Types:WrongValue"]
error = '''
Input value is in wrong format
'''

